const SOURCE_TRUTH = Object.freeze({
  work: "Homeros, Odysseia",
  canonicalScope: "Odysseia'nın Truva sonrası dönüş yolculuğuna ilişkin genel çerçevesi",
  primaryText: {
    title: "Homer, Odyssey",
    edition: "A. T. Murray, Greek text and English translation, 1919",
    repository: "Perseus Digital Library",
    licenseNote: "Perseus üzerindeki açık lisanslı metin yalnızca olay ve karakter doğrulaması için kullanılır.",
  },
  turkishReference: {
    title: "Odysseia",
    translators: "Azra Erhat ve A. Kadir",
    useRestriction: "Modern Türkçe çeviri kopyalanmaz; yalnızca karşılaştırmalı doğrulamada kullanılır.",
  },
  adaptationPolicy: "Okurio metinleri özgün yeniden anlatımdır; hiçbir modern çeviriden cümle alınmaz.",
  verificationStatus: "source-reviewed",
});

const SHARED_REVIEW = Object.freeze({
  productOwnerApproved: false,
  accessibilityApproved: false,
  dyslexiaExperienceApproved: false,
  adhdExperienceApproved: false,
  socialEmotionalReviewStatus: "not-applicable",
  clinicalBoundaryChecked: true,
  copyrightChecked: true,
  sourceTruth: SOURCE_TRUTH,
  aiEditorialPreReviewStatus: "completed",
  lexiconExpertReviewStatus: "pending-human-review",
  literaryEditorReviewStatus: "pending-human-review",
  publicationGate: "expert-signoff-required",
});

export const ODYSSEY_STORIES = [
  {
    legacy: {
      id: "odysseia-01-cocuk-truvadan-ayrilis",
      baslik: "Odysseia: Eve Doğru İlk Rüzgâr",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Mitoloji ve Keşif",
      yas: "7-10 yaş",
      renk: ["#274C77", "#A3CEF1"],
      puan: 5,
      sureDk: 5,
      ozet: "Odysseus, savaşın ardından eve dönmek için yola çıkarken hazırlığın, sabrın ve dayanışmanın değerini keşfeder.",
      bolumler: [
        {
          ad: "Sönen Ateşlerin Ardında",
          dk: 1,
          metin: "Truva'nın yüksek surları sabahın solgun ışığında sessiz görünüyordu. On yıl boyunca kentin çevresinde çadırlar kurulmuştu. Şimdi çadırlar sökülmüş, savaş ateşleri yavaş yavaş sönmüştü. Odysseus kıyıda durup denizi izledi. Önünde parlayan su ona hem eve dönüşü hem de bilinmeyen yolları hatırlatıyordu. İthaka uzaktaydı; orada eşi Penelope ve oğlu Telemakhos onu bekliyordu. Odysseus, ‘Zafer kazandık ama yolculuğumuz henüz bitmedi,’ dedi. Denizciler onun çevresinde toplandı. Hepsi evlerini özlemişti. Yine de acele etmenin tehlikeli olacağını biliyorlardı. Önce gemileri, yiyecekleri ve su kaplarını dikkatle kontrol etmeleri gerekiyordu.",
        },
        {
          ad: "İthaka'yı Hatırlamak",
          dk: 1,
          metin: "Odysseus gözlerini kapattığında İthaka'yı düşündü. Kayalık kıyıları, zeytin ağaçlarını ve evinin avlusunu hatırladı. Telemakhos'u en son küçük bir çocukken görmüştü. Şimdi ne kadar büyüdüğünü bilmiyordu. Penelope'nin sabırlı sesini anımsadı. Bu düşünceler ona güç verdi, fakat aynı zamanda sorumluluğunu da hatırlattı. Gemilerde yalnızca kendi hayatı yoktu. Yanında yolculuk eden herkesin güvenliği de ona bağlıydı. Bu yüzden denizcilere görevlerini tek tek anlattı. Kimisi halatları kontrol edecek, kimisi kürekleri sayacaktı. Kimisi de su kaplarının ağzını sıkıca kapatacaktı. ‘Eve ulaşmak istiyorsak birbirimize dikkat etmeliyiz,’ dedi.",
        },
        {
          ad: "Küçük Çatlak",
          dk: 1,
          metin: "Genç bir denizci, yiyecek çuvallarından birinin ıslandığını fark etti. Çuvalın altındaki tahtadan ince bir su sızıntısı geliyordu. Bazıları, ‘Bir çatlaktan ne olur, hemen yola çıkalım,’ diye düşündü. Odysseus ise eğilip tahtayı inceledi. Küçük çatlak büyürse ambarı su basabilirdi. Yolculuk sırasında yiyecekler bozulur, gemi de ağırlaşırdı. Usta marangoz çağrıldı. Çatlak temizlendi, yeni bir tahta parçası yerleştirildi ve reçineyle kapatıldı. Bu iş biraz zaman aldı. Güneş yükselirken denizciler sabırsızlandı. Fakat onarım bittiğinde herkes küçük bir ayrıntının büyük bir sorunu önlediğini anladı. Odysseus, ‘Dikkat, korkmak değildir. Dikkat, yolculuğa saygı göstermektir,’ dedi.",
        },
        {
          ad: "Rüzgârı Dinlemek",
          dk: 1,
          metin: "Öğleye doğru hafif bir rüzgâr çıktı. Yelkenler hemen açılmadı. Odysseus önce gökyüzündeki bulutlara, sonra dalgaların yönüne baktı. Yaşlı dümenci de avucunu rüzgâra çevirdi. Rüzgâr kıyıdan denize doğru esiyor, fakat ara sıra yön değiştiriyordu. Bir süre beklediler. Denizciler bu sırada kürekleri yerlerine koydu ve gemiler arasındaki işaretleri tekrar etti. Bir gemi tehlike görürse kırmızı bez kaldıracaktı. Suya ihtiyaç duyarsa iki kez boru çalacaktı. Herkes ne yapacağını bilince yolculuk daha güvenli olacaktı. Sonunda rüzgâr kararlı bir biçimde yelkenleri doldurdu. Odysseus başını salladı. Artık ayrılma vakti gelmişti.",
        },
        {
          ad: "İlk Yelken",
          dk: 1,
          metin: "Gemiler kıyıdan birer birer uzaklaştı. Kürekler suya aynı ritimle girip çıktı. Truva'nın kuleleri önce küçüldü, sonra sisin içinde soluk bir çizgiye dönüştü. Bazı denizciler geriye baktı; bazıları yalnızca önlerindeki ufka odaklandı. Odysseus iki duyguyu birden taşıyordu: Geride kalanların hüznü ve eve dönmenin umudu. Deniz ilk saatlerde sakindi. Martılar gemilerin çevresinde uçuyor, güneş suyun üzerinde parlak yollar çiziyordu. Genç denizci onarılan ambarı yeniden kontrol etti. İçerisi kuru kalmıştı. Gülümsedi ve arkadaşına, ‘İyi ki acele etmemişiz,’ dedi. Böylece hazırlığın değeri daha yolculuğun ilk gününde anlaşılmış oldu.",
        },
        {
          ad: "Mavi Bilmece",
          dk: 1,
          metin: "Akşam yaklaşırken kıyı gözden kayboldu. Her yönde yalnızca deniz vardı. Ufuk, gökyüzüyle suyun birleştiği ince bir çember gibi görünüyordu. Bazı denizciler bu sonsuzluk karşısında huzursuz oldu. Odysseus onların yanına gidip İthaka'yı anlattı. Ona küçük limanı, taş yolları ve rüzgârda sallanan ağaçları anlattı. Herkes kendi evini düşünmeye başladı. Korkuları tamamen kaybolmadı, ama ortak bir amaçları olduğunu yeniden hatırladılar. Odysseus, yolculuğun yalnızca güçlü olmakla tamamlanamayacağını biliyordu. Sabır, dikkat ve dayanışma da gerekliydi. İlk yıldız görünürken nöbetçiler yerlerini aldı. Gemiler karanlık denizde ilerledi. Eve giden yol daha yeni başlıyordu. Deniz, önlerinde çözülmeyi bekleyen mavi bir bilmeceydi.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "7-10",
      estimatedMinutes: 5,
      pilotEligible: true,
      contentTrack: "mythology-vocabulary-growth",
      primaryDevelopmentTheme: "hopeful-beginnings-and-careful-preparation",
      contentStatus: "editorially-mature-expert-signoff-pending",
      characters: ["Odysseus", "Penelope", "Telemakhos", "Akha denizcileri"],
      glossary: [
        { word: "sur", definition: "Bir kenti korumak için çevresine yapılan yüksek ve sağlam duvardır." },
        { word: "ambar", definition: "Gemide yiyecek ve malzemelerin saklandığı bölümdür." },
        { word: "reçine", definition: "Bazı ağaçlardan çıkan ve yüzeyleri kapatmak için kullanılabilen yapışkan maddedir." },
        { word: "dümenci", definition: "Geminin yönünü dümenle belirleyen kişidir." },
        { word: "ufuk", definition: "Gökyüzüyle yerin birleşiyor gibi göründüğü uzak çizgidir." },
        { word: "dayanışma", definition: "İnsanların ortak bir amaç için birbirine destek olmasıdır." },
      ],
      optionalReflectionPrompt: "Odysseus küçük çatlağı neden önemsemiş olabilir?",
      vocabularyPlan: {
        targetLevel: "temel-zenginleşen",
        recurrence: ["ufuk", "hazırlık", "dayanışma"],
        reviewOwner: "Türkçe dil ve çocuk edebiyatı uzmanı",
      },
      reviewNotes: [
        "Olay örgüsü tek çizgide ve kısa bölümlerle sürdürüldü.",
        "Savaş ayrıntıları yaş grubuna uygun biçimde sınırlandırıldı.",
        "Her bölüm tek ana düşünce taşıyacak şekilde erişilebilirlik ön incelemesinden geçirildi.",
        "2026-08-06: 6 cümle 12 kelime/cümle sözlük planı sınırını aşıyordu; anlam korunarak ikiye bölündü. scripts/validate-pilot-content.mjs artık ihlalsiz geçiyor.",
        "Nihai yayın, insan uzman imzasına bağlıdır.",
      ],
    },
  },
  {
    legacy: {
      id: "odysseia-01-genc-truvadan-ayrilis",
      baslik: "Odysseia: Zaferden Sonraki Belirsizlik",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Mitoloji, Karakter ve Strateji",
      yas: "11-16 yaş",
      renk: ["#243B53", "#9FB3C8"],
      puan: 5,
      sureDk: 9,
      ozet: "Odysseus, zaferin dönüş anlamına gelmediğini fark eder; sorumluluk, hazırlık ve ortak kararlarla belirsiz denize açılır.",
      bolumler: [
        {
          ad: "Zaferin Sessizliği",
          dk: 1,
          metin: "Truva'nın düşmesinden sonraki sabah, kıyıda alışılmadık bir sessizlik vardı. Yıllarca savaşın gürültüsüne alışan askerler bu sessizlikte ne hissedeceklerini bilmiyordu. Bazıları zaferi kutluyor, bazıları kaybettikleri arkadaşlarını düşünüyordu. Odysseus, gemilerin bulunduğu koya doğru yürüdü. İthaka'ya dönme düşüncesi içini umutla doldursa da önündeki denizin zaferden daha farklı bir sınav olduğunu biliyordu. Karada düşman görünürdü; denizde ise tehlike çoğu zaman rüzgârın, akıntının ya da yanlış bir kararın içine saklanırdı. Bu yüzden dönüşü bir kaçış değil, yeni bir sorumluluk olarak gördü.",
        },
        {
          ad: "Komutanın Hesabı",
          dk: 1,
          metin: "Odysseus her geminin durumunu ayrı ayrı inceledi. Yelken bezleri güneşte açıldı, halatlar gerildi, küreklerin çatlakları arandı. Erzak listeleri yeniden sayıldı. Bazı denizciler bu denetimi gereksiz buldu; savaş bitmişti ve herkes bir an önce evine ulaşmak istiyordu. Odysseus ise acele ile cesaretin aynı şey olmadığını söyledi. Cesaret, tehlikeyi görmezden gelmek değil, onu doğru ölçmekti. Gemilerden birinde sızıntı, diğerinde eksik su kabı bulundu. Küçük kusurlar giderilirken gecikme arttı, fakat yolculuğun ilk günlerinde yaşanabilecek daha büyük sorunların önüne geçildi. Disiplin, belirsizlik karşısındaki ilk savunmalarıydı.",
        },
        {
          ad: "İthaka'nın Çağrısı",
          dk: 1,
          metin: "Hazırlık sürerken Odysseus kıyının daha sakin bir yerine çekildi. İthaka'yı yalnızca bir ada olarak düşünmüyordu. Orada ailesi, geçmişi, verdiği sözler ve yeniden üstlenmesi gereken görevler vardı. Telemakhos'u küçük yaşta bırakmıştı; şimdi karşısına nasıl bir genç çıkacağını bilmiyordu. Penelope'nin yıllar boyunca nasıl yaşadığını da ancak tahmin edebilirdi. Dönüş, kaldığı yerden devam etmek değildi. Uzun bir ayrılıktan sonra herkes değişmişti. Odysseus, eve varmanın önce bu değişimi kabul etmeyi gerektirdiğini sezdi. Bu düşünce onu hem güçlendirdi hem de huzursuz etti. Çünkü bazen insan en çok özlediği yere dönerken bile kendinden emin olamazdı.",
        },
        {
          ad: "Küçük İhmalin Bedeli",
          dk: 1,
          metin: "Öğleye doğru genç bir tayfa, erzak ambarındaki ıslaklığı fark etti. Alt tahtalardan biri çatlamıştı. Birkaç kişi, çatlağın küçük olduğunu ve ilk limanda onarılabileceğini savundu. Odysseus buna karşı çıktı. Uzun yolculuklarda sorunlar tek başına kalmaz, birbirini büyütürdü. Su yiyecekleri bozabilir, bozulan erzak denizcileri güçsüz bırakabilir, güçsüzlük de yanlış kararlara yol açabilirdi. Marangozlar tahtayı değiştirdi, reçineyle yalıttı ve ambarı yeniden düzenledi. Bu sırada Odysseus tayfalara neden beklediklerini açıkladı. Emir vermekle yetinmeyip kararının gerekçesini paylaşması, huzursuzluğu azalttı. Mürettebat, güvenin yalnızca komutana inanmak değil, kararın mantığını anlamakla da güçlendiğini gördü.",
        },
        {
          ad: "Ortak Karar",
          dk: 1,
          metin: "Akşamüstü rüzgâr kuvvetlendi. Bazı kaptanlar hemen açılmayı, bazıları ise sabahı beklemeyi önerdi. Odysseus görüşleri tek tek dinledi. Yaşlı dümenci, kıyıya yakın akıntının gece değişebileceğini söyledi. Başka bir kaptan, bulutların fırtına değil kısa süreli bir rüzgâr getirdiğini düşündü. Odysseus gökyüzünü, dalgaları ve gemilerin hazır oluşunu birlikte değerlendirdi. Sonunda gün batımından önce koydan çıkmaya, geceyi açık denize ulaşmadan korunaklı bir kıyı boyunca ilerleyerek geçirmeye karar verdi. Bu çözüm ne en hızlı ne de en yavaş seçenekti. Fakat farklı bilgileri ortak bir planda birleştiriyordu. Mürettebat kararın oluşumuna tanık olduğu için görevlerini daha dikkatli üstlendi.",
        },
        {
          ad: "Ayrılış",
          dk: 1,
          metin: "Yelkenler açıldığında kıyıda uzun gölgeler oluşmuştu. Gemiler birer birer hareket etti. Küreklerin düzenli sesi, geride kalan sessizliği böldü. Truva'nın surları uzaklaştıkça zaferin coşkusu da yerini daha karmaşık duygulara bıraktı. Denizcilerden biri geriye bakarak kaybettikleri arkadaşlarının adlarını fısıldadı. Bir başkası, evinde onu bekleyen çocuklarını anlattı. Odysseus kimseyi susturmadı. Yolculuğun yalnızca bedenleri değil, hatıraları da taşıdığını biliyordu. İnsanlar aynı gemide olsalar bile farklı yüklerle yol alıyordu. Ortak rota, bu farklılıkları yok etmiyor; onları aynı amaç çevresinde bir arada tutuyordu.",
        },
        {
          ad: "Ufukta İlk Gece",
          dk: 1,
          metin: "Gece çöktüğünde Truva artık görünmüyordu. Gökyüzündeki yıldızlar denizcilere yön gösterirken ufuk karanlık bir çember gibi gemileri çevreledi. Bazı tayfalar bilinmeyenden korktu. Odysseus nöbet düzenini yeniden kontrol etti ve herkesin dinlenebilmesi için görevleri eşit biçimde dağıttı. Sonra güvertede sessizce oturdu. Zafer, geçmişte kalan bir sonuçtu; dönüş ise her gün yeniden kurulacak bir süreçti. Bunun için yalnızca zekâ değil, sabır, dayanışma ve gerektiğinde fikrini değiştirebilme gücü gerekiyordu. İlk gecenin sonunda Odysseus şunu anladı: İthaka'ya giden yol haritada çizilebilir. Fakat insanın eve gerçekten dönebilmesi için sorumluluğunu da yanında taşıması gerekirdi.",
        },
        {
          ad: "İlk Sabahın Dersi",
          dk: 1,
          metin: "Sabah ilk ışıkla birlikte erzak dağıtımı yapıldı. Bazı denizciler daha fazla pay istedi; uzun süredir aç kaldıklarını söylediler. Odysseus herkese eşit miktar verilmesi gerektiğini açıkladı. Eşitsiz paylaşım, küçük bir huzursuzluğu büyük bir anlaşmazlığa dönüştürebilirdi. Yaşlı bir denizci gençlere neden sabırlı olmaları gerektiğini anlattı. Yolculuk daha yeni başlamıştı ve erzak azaldıkça herkesin ihtiyacı artacaktı. Odysseus bu konuşmayı dikkatle dinledi, sonra kendi payından bir kısmını en genç tayfaya ayırdı. Küçük bir jest, sözlerin ötesinde bir güven inşa etti. Mürettebat, adaletin yalnızca kural koymak değil, örnek olmakla da kurulduğunu gördü. Bu ilk sabahın dersi, geri kalan yolculuk boyunca hatırlanacaktı.",
        },
        {
          ad: "Uzak Kıyının İşareti",
          dk: 1,
          metin: "Öğleden sonra ufukta ince bir duman sütunu belirdi. Kimileri hemen oraya yönelmek istedi; bilinmeyen bir kıyıda su ve taze erzak bulabilirlerdi. Odysseus önce temkinli davranmayı seçti. Tanımadıkları bir toprağa aceleyle yaklaşmanın riskli olabileceğini hatırlattı. Önce iki kürekçi gönderdi; kıyıyı uzaktan gözlemlediler ve geri döndüler. Anlattıklarına göre kıyı sakin görünüyordu, ama yerleşim yerinden emin değillerdi. Odysseus, gemilerin açıkta beklemesine, yalnızca küçük bir grubun dikkatle kıyıya çıkmasına karar verdi. Bu temkinli yaklaşım bazı tayfaları sabırsızlandırdı. Fakat Odysseus, bilinmeyenle karşılaşırken hız yerine dikkatin daha değerli olduğunu biliyordu.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "11-16",
      estimatedMinutes: 9,
      pilotEligible: false,
      contentTrack: "mythology-critical-reading",
      primaryDevelopmentTheme: "responsibility-under-uncertainty",
      contentStatus: "editorially-mature-expert-signoff-pending",
      characters: ["Odysseus", "Penelope", "Telemakhos", "Akha mürettebatı"],
      glossary: [
        { word: "ihmal", definition: "Gerekli ilgiyi veya özeni göstermeme durumudur." },
        { word: "sorumluluk", definition: "Bir görevin sonucunu üstlenme ve gereğini yapma durumudur." },
        { word: "akıntı", definition: "Deniz suyunun belirli bir yönde sürekli hareket etmesidir." },
        { word: "mürettebat", definition: "Bir gemide birlikte görev yapan insanların tümüdür." },
        { word: "gerekçe", definition: "Bir kararın veya düşüncenin dayandığı açıklanabilir nedendir." },
        { word: "dayanışma", definition: "İnsanların ortak amaç için birbirini desteklemesidir." },
      ],
      optionalReflectionPrompt: "Odysseus'un kararlarını açıklaması mürettebatın güvenini nasıl etkiledi?",
      vocabularyPlan: {
        targetLevel: "orta-ileri",
        recurrence: ["sorumluluk", "gerekçe", "dayanışma"],
        reviewOwner: "Türkçe eğitimi ve gençlik edebiyatı uzmanı",
      },
      reviewNotes: [
        "Her bölüm tek karar veya duygu ekseninde tutuldu.",
        "Soyut kavramlar somut olaylarla ilişkilendirildi.",
        "Strateji ve liderlik temaları didaktik bir tona dönüşmeden işlendi.",
        "2026-08-06: 235sn olan süre 300sn eşiğinin altındaydı; \"İlk Sabahın Dersi\" ve \"Uzak Kıyının İşareti\" adlı 2 yeni bölümle 311sn'e çıkarıldı (kaynak kapsamı genişletilmedi, yalnızca dönüş yolculuğunun genel çerçevesi içinde özgün anlatım). 1 uzun cümle ayrıca ikiye bölündü.",
        "Nihai yayın, insan uzman imzasına bağlıdır.",
      ],
    },
  },
  {
    legacy: {
      id: "odysseia-01-yetiskin-truvadan-ayrilis",
      baslik: "Odysseia: Dönüşün Başladığı Kıyı",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Klasikler, Mitoloji ve Düşünce",
      yas: "16+ yaş",
      renk: ["#1B263B", "#778DA9"],
      puan: 5,
      sureDk: 11,
      ozet: "Zaferin küllerinden ayrılan Odysseus, eve dönüşün aidiyet, değişim, liderlik ve metanetle örülü yeni bir sınav olduğunu kavrar.",
      bolumler: [
        {
          ad: "Küllerin Ardından",
          dk: 1,
          metin: "Truva'nın üzerinde yükselen duman, şafakla birlikte ağır bir perdeye dönüşmüştü. Yıllarca erişilmez görünen surlar artık sessizdi. Zafer, uzaktan bakıldığında kesin bir sonuç gibi duruyordu; yakından ise yorgunluk, kayıp ve cevapsız sorular taşıyordu. Odysseus kıyıya inerken askerlerin yüzlerini inceledi. Bazılarında sevinç, bazılarında boşluk vardı. On yıl boyunca tek amaç etrafında yaşayan insanlar şimdi ne yapacaklarını yeniden öğrenmek zorundaydı. Savaş bitmişti, fakat savaşın insanlarda açtığı değişim sona ermemişti. Odysseus için eve dönüş, yalnızca gemileri İthaka yönüne çevirmek değildi. Önce zaferin geride bıraktığı ağırlığı tanımak gerekiyordu.",
        },
        {
          ad: "Aidiyetin Hafızası",
          dk: 1,
          metin: "Denizin karşısında durduğunda İthaka zihninde bir haritadan çok bir hafıza olarak belirdi. Kayalık kıyılar, zeytin ağaçları, sarayın avlusunda değişen ışık ve Penelope'nin sesi birbirine karıştı. Telemakhos'u küçük bir çocukken bırakmıştı. Şimdi babasını tanıyacak yaşa gelmiş olmalıydı. Odysseus, özlemin geçmişi olduğu gibi koruduğunu, hayatın ise insanları sessizce değiştirdiğini düşündü. Dönen kişi de bekleyenler de aynı kalmamıştı. Aidiyet bu nedenle yalnızca bir yere sahip olmak değil, değişmiş hâlinle o yere yeniden bağ kurabilmekti. İthaka'nın çağrısı güçlüydü; fakat bu çağrı ona aynı zamanda hesabı verilmemiş yılları ve yeniden kurulması gereken ilişkileri hatırlatıyordu.",
        },
        {
          ad: "Ferasetin Sınavı",
          dk: 1,
          metin: "Gemilerin denetimi başladığında Odysseus ayrıntılara olağanüstü bir dikkat gösterdi. Halatların liflerini, yelkenlerin dikişlerini, küreklerin dengesini ve ambarların kuruluğunu kontrol ettirdi. Mürettebatın bir bölümü bunu savaş sonrasındaki gereksiz bir titizlik sayıyordu. Oysa Odysseus, açık denizde büyük felaketlerin çoğu zaman küçük bir ihmalin çevresinde büyüdüğünü biliyordu. Feraset, yalnızca görünmeyeni sezmek değildi; sezgiyi kanıt, deneyim ve ölçüyle sınamaktı. Bir gemide bulunan ince çatlak, acele edilse fark edilmeyecekti. Tahta değiştirildiğinde yolculuk birkaç saat gecikti. Ancak bu gecikme, ileride yiyeceği, güvenliği ve insan gücünü koruyacak bir yatırıma dönüştü.",
        },
        {
          ad: "Emir ile Güven Arasında",
          dk: 1,
          metin: "Odysseus onarım kararını yalnızca buyurmadı; nedenini mürettebata açıkladı. Uzun savaş boyunca emirlerin çoğu tartışmaya kapalı olmuştu. Dönüş yolculuğu ise başka bir liderlik dili gerektiriyordu. İnsanlar yorgundu ve artık yalnızca zafer sözüyle harekete geçirilemezdi. Kararların anlamını bilmek, onlara yeniden özne olduklarını hatırlatıyordu. Odysseus farklı kaptanların görüşlerini dinledi, riskleri karşılaştırdı ve hangi belirsizliği neden kabul ettiğini anlattı. Bu yaklaşım otoritesini azaltmadı; aksine güveni kişisel bağlılıktan ortak kavrayışa taşıdı. Mürettebat, komutanın her şeyi bildiğine değil, bilmediğini de hesaba kattığına inanmaya başladı.",
        },
        {
          ad: "Rüzgârın Kararı",
          dk: 1,
          metin: "Akşamüstü rüzgâr sertleşirken gökyüzünde uzun bulut şeritleri oluştu. Kaptanlar ikiye ayrıldı. Bir kısmı uygun rüzgârı kaçırmadan açılmak istiyor, diğerleri geceyi kıyıda geçirmenin daha güvenli olduğunu savunuyordu. Odysseus tek bir işarete bakarak karar vermedi. Akıntıyı, gemilerin yükünü, mürettebatın yorgunluğunu ve korunaklı kıyıların konumunu birlikte değerlendirdi. Sonunda koydan çıkmaya, fakat açık denize yönelmeden kıyı boyunca ilerlemeye karar verdi. Bu karar kesinlik iddiası taşımıyordu; eldeki bilgilerle kurulmuş, gerektiğinde değiştirilebilecek bir plandı. Belirsizlik karşısında bilgelik, her zaman doğruyu bilmekten çok, yanılma payını yönetebilmekti.",
        },
        {
          ad: "Ayrılığın Ağırlığı",
          dk: 1,
          metin: "Gemiler hareket ettiğinde Truva kıyısında uzun gölgeler kaldı. Küreklerin düzenli sesi, savaşın düzensiz gürültüsünden bütünüyle farklıydı. Denizcilerden bazıları geriye bakıyor, bazıları bakmamayı seçiyordu. Her biri yanında görünmeyen bir yük taşıyordu: kaybettikleri insanlar, verdikleri kararlar, söyleyemedikleri sözler. Odysseus bu sessizliği bozmadı. Bir topluluğu yönetmenin her duyguyu çözmek anlamına gelmediğini biliyordu. Bazen yapılabilecek en doğru şey, insanların yüklerini inkâr etmeden ortak yönü korumaktı. İthaka onların aynı hedefiydi; fakat herkes o hedefe farklı bir geçmişten geliyordu. Ortak rota, kişisel acıları silmiyor, yalnızca onlara hareket edebilecekleri bir çerçeve veriyordu.",
        },
        {
          ad: "Dönüşün Çelişkisi",
          dk: 1,
          metin: "Kıyı küçüldükçe Odysseus, dönüş fikrinin içinde taşıdığı çelişkiyi daha açık gördü. İnsan eve dönmek ister, çünkü orada kendisine ait bir düzen bulunduğuna inanır. Fakat uzun ayrılıklar hem evi hem de insanı değiştirir. Bu yüzden dönüş, geçmişe geri gitmek değil, geçmişle bugünün arasında yeni bir ilişki kurmaktır. Odysseus İthaka'da kendisini nasıl bir düzenin beklediğini bilmiyordu. Kral olarak sorumlulukları, eş ve baba olarak eksikleri vardı. Zafer ona bu soruların hiçbirini cevaplamamıştı. Deniz yolculuğu, dışarıdaki engeller kadar içerideki belirsizliklerle de yüzleşeceği bir alan olacaktı.",
        },
        {
          ad: "İlk Gece ve Metanet",
          dk: 1,
          metin: "Gece çöktüğünde yıldızlar açık denizin üzerinde keskinleşti. Nöbetçiler yerlerini aldı, yorgun denizciler dar güvertelerde uyumaya çalıştı. Odysseus uyumadan önce gemilerin sırasını, rüzgârın değişimini ve ertesi günün rotasını yeniden düşündü. Akıl, olasılıkları tartmasına yardım ediyordu; fakat her şeyi kontrol edemeyeceğini de biliyordu. Metanet, kontrol edilemeyen karşısında katılaşmak değil, kırılmadan uyum sağlayabilmekti. İlk gece sakin geçti. Yine de Odysseus bunun geleceğe ilişkin bir güvence olmadığını biliyordu. Ufuk hem vaat hem tehdit taşıyordu. Eve dönüş başlamıştı; fakat yolun onu hangi kıyılara, hangi kayıplara ve hangi hakikatlere götüreceği henüz bilinmiyordu.",
        },
        {
          ad: "Payların Adaleti",
          dk: 1,
          metin: "Şafak sökerken erzak dağıtımı gündeme geldi ve bu, savaşın bittiği ama eşitliğin henüz kurulmadığı bir topluluğun ilk sınavlarından biri oldu. Bazı denizciler, uzun kuşatma boyunca çektikleri açlığı öne sürerek daha büyük pay talep ettiler; bu talep haksız değildi, fakat karşılanması hâlihazırda kısıtlı olan kaynakları tüketebilirdi. Odysseus, kısa vadeli bir rahatlamanın uzun vadeli bir krize dönüşebileceğini biliyordu ve bu yüzden eşit paylaşımda ısrar etti. Kararını yalnızca buyurmadı; erzak stoklarını herkesin görebileceği biçimde açıkça sergiledi, azalan miktarı hesapladı ve önümüzdeki günlerin belirsizliğini paylaştı. Şeffaflık, itaatten daha kalıcı bir düzen kurdu: insanlar yalnızca emre değil, gördükleri gerçeğe inandılar.",
        },
        {
          ad: "Bilinmeyen Kıyının Sınaması",
          dk: 1,
          metin: "Öğleden sonra ufukta beliren ince bir duman sütunu, mürettebatın çoğunda hem umut hem tedirginlik uyandırdı; bilinmeyen bir kıyı hem tazelenme imkânı hem de öngörülemeyen bir tehlike anlamına gelebilirdi. Bazı kaptanlar hemen yönelmek isterken Odysseus, ihtiyatın bazen cesaretten daha değerli olduğunu hatırlattı. Küçük bir keşif grubu gönderdi; kıyıyı uzaktan gözlemlemelerini, yerleşim izlerine dikkat etmelerini ve gereksiz risk almamalarını istedi. Grup döndüğünde kıyının sessiz göründüğünü, ancak kimin yaşadığının belirsiz kaldığını bildirdi. Odysseus, gemilerin çoğunu açıkta bekletmeye, yalnızca sınırlı bir grupla temkinli biçimde karaya çıkmaya karar verdi. Bu seçim hız kaybettirse de, bilinmeyenle karşılaşmanın bedelini en aza indiriyordu.",
        },
        {
          ad: "Geceye Bırakılan Sorular",
          dk: 1,
          metin: "Gecenin ilk saatlerinde, gündüzün kararları Odysseus'un zihninde yeniden şekillendi; her seçim doğru görünse de, denizin belirsizliği hiçbir kararı kesin kılmıyordu. Genç bir denizci ona yaklaşarak, bunca ihtiyat ve hesaplılığın yorucu olup olmadığını sordu. Odysseus, gücün her zaman kesin bilmekten değil, bilmediğini kabul edip yine de sorumluluk almaktan geldiğini söyledi. Bu cevap genç adamı hem rahatlattı hem de şaşırttı; bir liderin de belirsizlik taşıyabileceğini o âna kadar düşünmemişti. Yıldızlar altında nöbet değişirken Odysseus, ertesi günün de benzer sınavlar getireceğini biliyordu. Dönüş, tek bir kararla değil, art arda gelen küçük ve büyük seçimlerle örülüyordu.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "16+",
      estimatedMinutes: 11,
      pilotEligible: false,
      contentTrack: "classics-literary-development",
      primaryDevelopmentTheme: "identity-belonging-and-resilient-return",
      contentStatus: "editorially-mature-expert-signoff-pending",
      characters: ["Odysseus", "Penelope", "Telemakhos", "Akha mürettebatı"],
      glossary: [
        { word: "aidiyet", definition: "Bir yere, topluluğa veya ilişkiye bağlılık ve kendini onun parçası sayma durumudur." },
        { word: "feraset", definition: "Olayların görünmeyen yönlerini sezgi, deneyim ve değerlendirmeyle kavrama gücüdür." },
        { word: "otorite", definition: "Karar verme, yönlendirme veya yönetme yetkisidir." },
        { word: "özne", definition: "Kendi kararlarını verebilen ve eylemlerinin sorumluluğunu taşıyan kişidir." },
        { word: "çelişki", definition: "Birbirine karşıt görünen düşünce veya durumların aynı anda bulunmasıdır." },
        { word: "metanet", definition: "Zorluklar karşısında dayanıklı, dengeli ve sakin kalabilme gücüdür." },
      ],
      optionalReflectionPrompt: "Metin, eve dönüşü neden geçmişe geri dönmekten farklı görüyor?",
      vocabularyPlan: {
        targetLevel: "ileri-edebi",
        recurrence: ["aidiyet", "feraset", "metanet"],
        reviewOwner: "Türk dili, sözlükbilim ve edebiyat uzmanı",
      },
      reviewNotes: [
        "Edebî yoğunluk kısa ve odaklı ekran bölümleri içinde dengelendi.",
        "Soyut temalar somut liderlik ve yolculuk kararları üzerinden geliştirildi.",
        "Modern Türkçe çevirilere özgü cümle kuruluşları kullanılmadı.",
        "2026-08-06: 258sn olan süre 360sn eşiğinin altındaydı; \"Payların Adaleti\", \"Bilinmeyen Kıyının Sınaması\" ve \"Geceye Bırakılan Sorular\" adlı 3 yeni bölümle 372sn'e çıkarıldı (aynı kaynak kapsamı ilkesiyle, yeni bir mitolojik olay/kaynak iddiası eklenmedi).",
        "Nihai yayın, sözlükbilimci ve edebiyat editörü imzasına bağlıdır.",
      ],
    },
  },
];
