const SOURCE_TRUTH = Object.freeze({
  work: "Homeros, Odysseia",
  canonicalScope: "Odysseia'nın Truva sonrası dönüş yolculuğuna ilişkin genel çerçevesi",
  primaryText: {
    title: "Homer, Odyssey",
    edition: "A. T. Murray, Greek text and English translation, 1919",
    repository: "Perseus Digital Library",
    licenseNote: "Perseus üzerindeki açık lisanslı metin yalnızca olay ve karakter doğrulaması için kullanılır.",
  },
  turkishReference: {
    title: "Odysseia",
    translators: "Azra Erhat ve A. Kadir",
    useRestriction: "Modern Türkçe çeviri kopyalanmaz; yalnızca karşılaştırmalı doğrulamada kullanılır.",
  },
  adaptationPolicy: "Okurio metinleri özgün yeniden anlatımdır; hiçbir modern çeviriden cümle alınmaz.",
  verificationStatus: "source-reviewed",
});

const SHARED_REVIEW = Object.freeze({
  productOwnerApproved: false,
  accessibilityApproved: false,
  dyslexiaExperienceApproved: false,
  adhdExperienceApproved: false,
  socialEmotionalReviewStatus: "not-applicable",
  clinicalBoundaryChecked: true,
  copyrightChecked: true,
  sourceTruth: SOURCE_TRUTH,
  lexiconExpertReviewStatus: "pending-human-review",
  literaryEditorReviewStatus: "pending-human-review",
  publicationGate: "expert-signoff-required",
});

export const ODYSSEY_STORIES = [
  {
    legacy: {
      id: "odysseia-01-cocuk-truvadan-ayrilis",
      baslik: "Odysseia: Eve Doğru İlk Rüzgâr",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Mitoloji ve Keşif",
      yas: "7-10 yaş",
      renk: ["#274C77", "#A3CEF1"],
      puan: 5,
      sureDk: 4,
      ozet: "Odysseus'un savaştan sonra İthaka'ya dönme umuduyla denize açılışı.",
      bolumler: [
        {
          ad: "Sönen Ateşler",
          dk: 1,
          metin: "Truva'nın yüksek kuleleri artık sessizdi. Savaşın ateşleri yavaşça sönüyordu. Odysseus uzaktaki denize baktı.",
        },
        {
          ad: "İthaka Özlemi",
          dk: 1,
          metin: "Onun aklında küçük İthaka adası vardı. Penelope ile Telemakhos orada bekliyordu. Eve dönüş düşüncesi kalbini ısıttı.",
        },
        {
          ad: "Gemiler Hazırlanıyor",
          dk: 1,
          metin: "Denizciler sağlam halatları dikkatle bağladı. Kürekler gemilerin yanlarına yerleştirildi. Ambarlara su ve yiyecek kondu.",
        },
        {
          ad: "Bilge Bir Uyarı",
          dk: 1,
          metin: "Odysseus yolculuğun kolay olmayacağını biliyordu. Deniz bazen dostça, bazen hırçın davranırdı. Bu yüzden herkesi dikkatli olmaya çağırdı.",
        },
        {
          ad: "İlk Yelken",
          dk: 1,
          metin: "Sabah rüzgârı beyaz yelkenleri doldurdu. Gemiler kıyıdan ağır ağır uzaklaştı. Truva ufukta küçücük kaldı.",
        },
        {
          ad: "Yeni Bir Yol",
          dk: 1,
          metin: "Deniz önlerinde mavi bir bilmeceydi. Her dalga yeni bir haber taşıyordu. Odysseus gözlerini eve giden yola çevirdi.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "7-10",
      estimatedMinutes: 4,
      pilotEligible: true,
      contentTrack: "mythology-vocabulary-growth",
      primaryDevelopmentTheme: "hopeful-beginnings-and-careful-preparation",
      contentStatus: "deployment-candidate",
      characters: ["Odysseus", "Penelope", "Telemakhos"],
      glossary: [
        { word: "kule", definition: "Yüksekten gözetmek veya korunmak için yapılan yapıdır." },
        { word: "ufuk", definition: "Gökyüzüyle yerin birleşiyor gibi göründüğü uzak çizgidir." },
        { word: "ambar", definition: "Gemide yiyecek ve malzemelerin saklandığı bölümdür." },
        { word: "hırçın", definition: "Sert, güçlü ve sakin olmayan davranışı anlatır." },
        { word: "yelken", definition: "Rüzgârla gemiyi ilerleten geniş kumaş parçadır." },
        { word: "bilmece", definition: "Cevabı düşünerek bulunması gereken gizemli sorudur." },
      ],
      optionalReflectionPrompt: "Odysseus yolculuk öncesinde neden hazırlık yaptı?",
      vocabularyPlan: {
        targetLevel: "temel-zenginleşen",
        recurrence: ["ufuk", "yelken", "yolculuk"],
        reviewOwner: "Türkçe dil ve çocuk edebiyatı uzmanı",
      },
      reviewNotes: [
        "Savaş ayrıntıları yaş grubuna uygun biçimde sınırlandırıldı.",
        "Ana olay örgüsü korunurken anlatım tamamen özgün kuruldu.",
        "Sözlük insan uzman imzası gelene kadar yayın kapısında bekler.",
      ],
    },
  },
  {
    legacy: {
      id: "odysseia-01-genc-truvadan-ayrilis",
      baslik: "Odysseia: Zaferden Sonraki Belirsizlik",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Mitoloji, Karakter ve Strateji",
      yas: "11-16 yaş",
      renk: ["#243B53", "#9FB3C8"],
      puan: 5,
      sureDk: 5,
      ozet: "Odysseus zaferin ardından eve dönüşün yeni sınavlarını düşünür.",
      bolumler: [
        {
          ad: "Zaferin Sessizliği",
          dk: 1,
          metin: "Truva düşmüş, savaşın gürültüsü geride kalmıştı. Fakat zafer, beklenen huzuru hemen getirmedi. Yorgun askerler evlerini düşünüyordu.",
        },
        {
          ad: "Komutanın Bakışı",
          dk: 1,
          metin: "Odysseus kıyıda duran gemileri inceledi. Her tekne uzun yol için hazırlanmalıydı. Küçük bir ihmal büyük sonuçlar doğurabilirdi.",
        },
        {
          ad: "İthaka'nın Çağrısı",
          dk: 1,
          metin: "İthaka onun için yalnızca bir ada değildi. Orada ailesi, geçmişi ve sorumlulukları bulunuyordu. Dönüş, kendi kimliğine yeniden kavuşmaktı.",
        },
        {
          ad: "Denizin İhtimalleri",
          dk: 1,
          metin: "Deniz açık, fakat geleceği kapalıydı. Rüzgâr yön değiştirebilir, kıyılar tehlike saklayabilirdi. Odysseus ihtimalleri sessizce tarttı.",
        },
        {
          ad: "Hazırlık ve Disiplin",
          dk: 1,
          metin: "Mürettebat halatları, kürekleri ve erzakı denetledi. Herkes kendi görevini yeniden öğrendi. Düzen, belirsizlik karşısındaki ilk savunmaydı.",
        },
        {
          ad: "Ayrılış",
          dk: 1,
          metin: "Şafakla birlikte yelkenler rüzgârı yakaladı. Gemiler Truva kıyılarından ağır ağır ayrıldı. Geride zafer, ileride sınavlar vardı.",
        },
        {
          ad: "İlk Karar",
          dk: 1,
          metin: "Odysseus rotasını eve çevirdi. Ancak yol yalnız haritalarla bulunmayacaktı. Sabır, muhakeme ve dayanışma da gerekecekti.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "11-16",
      estimatedMinutes: 5,
      pilotEligible: true,
      contentTrack: "mythology-critical-reading",
      primaryDevelopmentTheme: "responsibility-under-uncertainty",
      contentStatus: "deployment-candidate",
      characters: ["Odysseus", "Penelope", "Telemakhos", "Akha mürettebatı"],
      glossary: [
        { word: "ihmal", definition: "Gerekli ilgiyi veya özeni göstermeme durumudur." },
        { word: "sorumluluk", definition: "Bir görevin sonucunu üstlenme ve gereğini yapmadır." },
        { word: "ihtimal", definition: "Bir olayın gerçekleşebilme olasılığıdır." },
        { word: "mürettebat", definition: "Bir gemide görev yapan insanların tümüdür." },
        { word: "erzak", definition: "Yolculuk için hazırlanan yiyecek ve temel ihtiyaçlardır." },
        { word: "muhakeme", definition: "Bilgileri değerlendirerek mantıklı sonuca ulaşma becerisidir." },
        { word: "dayanışma", definition: "İnsanların ortak amaç için birbirini desteklemesidir." },
      ],
      optionalReflectionPrompt: "Zafer neden Odysseus'un yolculuğunu tamamlamadı?",
      vocabularyPlan: {
        targetLevel: "orta-ileri",
        recurrence: ["ihtimal", "muhakeme", "sorumluluk"],
        reviewOwner: "Türkçe eğitimi ve gençlik edebiyatı uzmanı",
      },
      reviewNotes: [
        "Zafer, sorumluluk ve kimlik kavramları dengeli işlendi.",
        "Modern çevirilere özgü cümle kuruluşları kullanılmadı.",
        "Sözlük tanımları uzman kontrolü öncesinde taslak statüsündedir.",
      ],
    },
  },
  {
    legacy: {
      id: "odysseia-01-yetiskin-truvadan-ayrilis",
      baslik: "Odysseia: Dönüşün Başladığı Kıyı",
      yazar: "Okurio Mitoloji Kütüphanesi",
      seslendiren: "Okurio Anlatıcı",
      kategori: "Klasikler, Mitoloji ve Düşünce",
      yas: "16+ yaş",
      renk: ["#1B263B", "#778DA9"],
      puan: 5,
      sureDk: 5,
      ozet: "Zaferin gölgesinde başlayan dönüş, aidiyet ve irade üzerine edebî anlatı.",
      bolumler: [
        {
          ad: "Küllerin Ardından",
          dk: 1,
          metin: "Truva'nın dumanı göğe ağır bir perde çekiyordu. Zafer, küller arasında parlaklığını yitirmişti. Sessizlik savaşın son hükmü gibiydi.",
        },
        {
          ad: "Dönüş Fikri",
          dk: 1,
          metin: "Odysseus gözlerini denizin karanlık mavisine çevirdi. İthaka artık bir mekândan fazlasıydı. Orası hafızasının ve aidiyetinin merkeziydi.",
        },
        {
          ad: "Zaferin Bedeli",
          dk: 1,
          metin: "On yıl süren mücadele herkesi değiştirmişti. Dönüşen insan, bıraktığı eve aynı kişi dönemezdi. Odysseus bu hakikati sezdi.",
        },
        {
          ad: "Feraset",
          dk: 1,
          metin: "Komutan gemileri tek tek denetledi. Feraset, görünmeyen tehlikeyi önceden tartmayı gerektirirdi. Deniz dikkatsizliği kolayca cezalandırabilirdi.",
        },
        {
          ad: "Ortak İrade",
          dk: 1,
          metin: "Mürettebat yorgundu, fakat eve dönmeye kararlıydı. Ortak irade dağınık korkuları bir araya topladı. Her görev yolculuğun kaderine bağlandı.",
        },
        {
          ad: "Şafağın Eşiği",
          dk: 1,
          metin: "Şafak, kıyının üzerine solgun ışık bıraktı. Yelkenler rüzgârla ilk kez gerildi. Gemiler ağır bir vedayla açıldı.",
        },
        {
          ad: "Ufkun Vaadi",
          dk: 1,
          metin: "Ufuk hem vaat, hem tehdit taşıyordu. Eve giden yol düz bir çizgi değildi. İnsan bazen dolanarak kendi merkezine ulaşırdı.",
        },
        {
          ad: "Metanet",
          dk: 1,
          metin: "Odysseus yolculuğun metanet isteyeceğini biliyordu. Akıl tek başına her fırtınayı dindiremezdi. Sabır, aklın zamana karşı dayanışıydı.",
        },
      ],
    },
    metadata: {
      ...SHARED_REVIEW,
      ageBand: "16+",
      estimatedMinutes: 5,
      pilotEligible: true,
      contentTrack: "classics-literary-development",
      primaryDevelopmentTheme: "identity-belonging-and-resilient-return",
      contentStatus: "deployment-candidate",
      characters: ["Odysseus", "Penelope", "Telemakhos", "Akha mürettebatı"],
      glossary: [
        { word: "aidiyet", definition: "Bir yere veya topluluğa bağlılık hissetme durumudur." },
        { word: "hakikat", definition: "Bir düşünceden bağımsız olarak var olan gerçektir." },
        { word: "feraset", definition: "Olayların görünmeyen yönlerini sezerek doğru değerlendirme gücüdür." },
        { word: "irade", definition: "Karar verme ve kararını sürdürme gücüdür." },
        { word: "metanet", definition: "Zorluklar karşısında dayanıklı ve sakin kalabilme gücüdür." },
        { word: "muhakeme", definition: "Bilgileri tartarak gerekçeli bir sonuca ulaşma sürecidir." },
        { word: "tehdit", definition: "Zarar verme ihtimali taşıyan durum veya işarettir." },
        { word: "merkez", definition: "Bir düşüncenin veya yaşamın temel dayanak noktasıdır." },
      ],
      optionalReflectionPrompt: "Dönüş, neden yalnızca bir yere varmak değildir?",
      vocabularyPlan: {
        targetLevel: "ileri-edebi",
        recurrence: ["aidiyet", "feraset", "metanet", "muhakeme"],
        reviewOwner: "Türk dili, sözlükbilim ve edebiyat uzmanı",
      },
      reviewNotes: [
        "Metin edebî yoğunluk ile ekran okunabilirliği arasında dengelendi.",
        "Felsefi yorumlar eserin ana dönüş temasından türetildi.",
        "Nihai yayın, sözlükbilimci ve edebiyat editörü imzasına bağlıdır.",
      ],
    },
  },
];
