const section = (ad, paragraphs) => ({ ad, metin: paragraphs.join("\n\n") });

export const OKI_MOON_MAP_QUALITY_DRAFT = {
  legacy: {
    id: "oki-ay-haritasi-quality-draft",
    baslik: "Oki ve Ay Haritası",
    yazar: "Okurio Özgün İçerik Ekibi",
    seslendiren: "Oki Anlatıcı",
    kategori: "Bilim Hikâyesi",
    yas: "10-12 yaş",
    sureDk: 4.9,
    ozet: "Oki, Ay yüzeyindeki izleri araştırır ve güvenilir bir keşif haritası hazırlar.",
    bolumler: [
      section("Penceredeki Soru", [
        "Oki, akşam penceresinde parlak Ay'ı yeniden gördü. Yüzeydeki koyu alanlar uzaktan açıkça seçiliyordu. Bazı yuvarlak izler de ışığı bölüyordu.",
        "Oki, bu izlerin bir anlamı olduğunu düşündü. Masaya kâğıt, kalem ve büyüteç koydu. Sonra Lili'yi küçük gözlemevine çağırdı.",
        "Lili gelince Oki ilk sorusunu açıkladı. Ay'ın üzerinde gerçek yollar var mıydı? Lili, önce gördüklerini kaydetmeyi önerdi.",
        "İkisi pencerenin önüne birlikte sakinçe oturdu. Her iz için küçük bir işaret çizdiler. Ancak çizim kısa sürede iyice karışmaya başladı.",
        "Oki, koyu alanları yanlışlıkla göl sanmıştı. Lili bunun yalnızca bir tahmin olduğunu söyledi. Güvenilir bir kaynak bulmaları gerekiyordu.",
        "Oki önce kendi çizimine yeniden dikkatle baktı. Koyu alanları aynı büyüklükte işaretlemişti. Oysa fotoğrafta sınırlar oldukça farklı görünüyordu.",
        "Lili her gözlem için ayrı renk önerdi. Böylece tahminler gerçek bilgilerle karışmayacaktı. Oki bu öneriyi hemen haritasına uyguladı.",
      ]),
      section("Haritanın İlk Anahtarı", [
        "Nana, masaya NASA'nın güncel Ay sayfasını açtı. Sayfada büyük kraterlerin ayrıntılı fotoğrafları bulunuyordu. Kraterler çoğunlukla çarpışmalarla oluşan çukurlardı.",
        "Bazı kraterlerin ortasında yüksek tepeler görülüyordu. Bazılarında ise geniş ve düz tabanlar vardı. Güneş ışığı kenarlarda uzun gölgeler oluşturuyordu.",
        "Oki, gölgelerin biçimleri belirginleştirdiğini hemen fark etti. Her koyu yer aynı yapıyı göstermiyordu. Bu yüzden tek renkle harita çizemezdi.",
        "Lili, işaretler için küçük bir anahtar hazırladı. Daireler kraterleri, taramalar koyu düzlükleri gösterecekti. Oklar ise ışığın yönünü belirtecekti.",
        "Nana koyu düzlüklerin maria diye adlandırıldığını açıkladı. Eski gözlemciler onları deniz sanmıştı. Bugün onların bazaltik alanlar olduğunu biliyoruz.",
        "Oki, yeni bilgiyi haritanın kenarına yazdı. Bir harita yalnız şekillerden oluşmuyordu. İşaretlerin anlamı da açıkça anlatılmalıydı.",
        "Kaynak sayfasındaki görüntüler farklı tarihlerde çekilmişti. Bazı gölgeler bu nedenle daha uzun görünüyordu. Lili her fotoğrafın açıklamasını dikkatle okudu.",
        "Oki yalnız güzel görüntülere bakmak istemiyordu. Bilginin nereden geldiğini de bilmeliydi. Bu yüzden kaynak adını defterine ekledi.",
      ]),
      section("Eksik Parçanın Peşinde", [
        "Ertesi akşam Ay daha farklı görünüyordu. Oki, haritasının değiştiğini düşünerek şaşırdı. Lili önce önceki çizimi yeniden inceledi.",
        "Kraterler yerindeydi, fakat aydınlık bölüm değişmişti. Ay kendi ışığını üretmiyordu. Güneşten gelen ışığı bize yansıtıyordu.",
        "Ay, Dünya çevresindeki yolunda ilerlemeye devam ediyordu. Biz aydınlık yarının farklı kısımlarını görüyorduk. Bu görünüşler Ay'ın evrelerini oluşturuyordu.",
        "Oki, ilk haritada tarihi yazmadığını sonunda fark etti. Bu eksik bilgi iki çizimi karşılaştırmayı zorlaştırmıştı. Haritasına tarih ve gözlem saati ekledi.",
        "Toto gözlemevine gelirken kırmızı bir fener getirdi. Parlak ışık gözlerini rahatsız edebilirdi. Bu yüzden feneri masadan uzağa koydular.",
        "Toto, kraterleri uzay şehirleri sanmıştı. Oki ona hemen yanlış demedi. Birlikte fotoğraftaki açıklamaları yeniden okudular.",
        "Açıklamalar kraterlerin çarpma izleri olduğunu gösteriyordu. Ay'da rüzgâr ve sıvı su etkisi azdı. Bu nedenle eski izler uzun süre korunabiliyordu.",
        "Toto, tahminiyle kanıt arasındaki farkı anladı. Haritaya soru işaretli bir kutu ekledi. Doğrulanmayan fikirler bu kutuda bekleyecekti.",
        "Kutudaki ilk soru koyu alanlarla ilgiliydi. Oki bunların neden farklı göründüğünü merak etti. Nana bazalt yüzeylerin ışığı farklı yansıttığını açıkladı.",
        "İkinci soru kraterlerin yaşını soruyordu. Kaynak bütün kraterlere aynı yaş vermiyordu. Arkadaşlar kesin olmayan sayıları haritaya yazmadı.",
      ]),
      section("Gölgelerin Gösterdiği", [
        "Üçüncü gözlemde Ay'ın kenarı daha net görünüyordu. Işık ile karanlık arasındaki çizgi uzanıyordu. Krater gölgeleri bu çizginin yakınında belirgindi.",
        "Oki, bazı kraterlerin genişliğini karşılaştırmak istedi. Ancak evdeki büyüteç gerçek ölçü veremezdi. Ölçek olmadan kesin sayı yazmamaya karar verdi.",
        "Lili, bunun haritayı eksik yapmadığını söyledi. Güvenilir çalışma, bilmediğini açıkça gösterebilirdi. Oki bu düşünceyi küçük bir notla ekledi.",
        "Nana, Ay'ın bize aynı yüzünü gösterdiğini anlattı. Ay'ın dönüşü ve dolanımı uyumlu ilerliyordu. Uzak tarafı Dünya'dan doğrudan göremiyorduk.",
        "Oki, görünmeyen yüzü hayal etmeye başladı. Sonra hayal ile gözlemi ayrı tutmayı hatırladı. Uzak taraf için uzay araçlarının görüntülerini açtılar.",
        "Harita artık daha düzenli görünüyordu. Kraterler, koyu düzlükler ve gölgeler ayrılmıştı. Her bilgi yanında kendi kaynağını taşıyordu.",
        "Oki haritayı uzaktan tekrar incelemeyi denedi. Çok küçük notlar okumayı zorlaştırıyordu. Lili önemli işaretleri daha geniş çizdi.",
        "Toto gereksiz süsleri kenardan kaldırmayı önerdi. Böylece gözler temel bilgilere kolayca ulaşıyordu. Harita artık daha sakin görünüyordu.",
      ]),
      section("Keşif Masası", [
        "Hafta sonunda üç arkadaş haritayı masaya yaydı. Oki gözlem tarihlerini sırayla okudu. Lili kullanılan işaretlerin anahtarını yeniden kontrol etti.",
        "Toto soru kutusundaki fikirleri tek tek sordu. Bazı soruların cevabı kaynaklarda bulunuyordu. Bazıları ise yeni gözlemler gerektiriyordu.",
        "Oki, ilk çizimin kusurlu olduğunu artık görüyordu. Yine de o çizimi çöpe atmadı. Çünkü değişen düşüncesini açıkça gösteriyordu.",
        "Nana, keşfin hazır cevap olmadığını söyledi. Merak, dikkatli gözlem ve doğrulama birlikte çalışıyordu. Arkadaşlar bu cümleyi haritanın altına yazdı.",
        "Sonra haritaya bir başlık seçtiler. Başlık, Ay'ın Değişmeyen İzleri oldu. Evreler değişse bile yüzey izleri yerindeydi.",
        "Oki son kez pencereden Ay'a baktı. Artık yalnız parlak bir daire görmüyordu. Sorularla dolu büyük bir yüzey görüyordu.",
        "Harita tamamlanmıştı, fakat merakları henüz bitmemişti. Bir sonraki gözlem için boş sayfa bıraktılar. Yeni bilgi gelince harita yeniden gelişecekti.",
        "Oki, çalışmayı okul panosunda paylaşmayı düşündü. Önce kaynak bağlantılarını yeniden denetleyeceklerdi. Sonra Nana'dan son bir görüş isteyeceklerdi.",
        "Arkadaşlar ertesi hafta yeniden buluşmaya söz verdi. Ay aynı sorulara yeni ayrıntılar ekleyebilirdi. Boş sayfa sessizce onları bekliyordu.",
      ]),
    ],
  },
  metadata: {
    ageBand: "10-12",
    primaryTheme: "kanıta dayalı gözlem ve doğrulama",
    contentType: "factual",
    contentStatus: "draft",
    releaseReady: false,
    sourceOfTruth: {
      name: "NASA Moon science collection",
      url: "https://science.nasa.gov/moon/facts/",
      supportingUrls: [
        "https://science.nasa.gov/moon/lunar-craters/",
        "https://science.nasa.gov/moon/moon-phases/",
        "https://science.nasa.gov/moon/viewing-tips/",
        "https://science.nasa.gov/moon/tidal-locking/",
      ],
      accessedAt: "2026-07-19",
      scope: "Ay'ın kraterleri, maria düzlükleri, evreleri, yansıyan ışığı ve eşzamanlı dönüşü.",
      factualReviewStatus: "pending_human_review",
    },
    rights: {
      status: "pending_human_review",
      claim: "Okurio için hazırlanmış özgün taslak; kaynaklar yalnız olgusal doğrulama içindir.",
    },
    glossary: [
      { word: "krater", definition: "Bir gök cismi çarpınca oluşabilen yuvarlak çukurdur." },
      { word: "maria", definition: "Ay üzerindeki geniş ve koyu bazalt düzlükleridir." },
      { word: "bazalt", definition: "Soğuyan lavdan oluşan koyu renkli kaya türüdür." },
      { word: "evre", definition: "Ay'ın aydınlık bölümünün Dünya'dan görünen biçimidir." },
      { word: "ölçek", definition: "Haritadaki uzaklığı gerçek uzaklıkla ilişkilendiren ölçüdür." },
      { word: "doğrulama", definition: "Bir bilgiyi güvenilir kanıtlarla yeniden kontrol etmektir." },
    ],
    optionalReflectionPrompt: "Oki hangi bilgisini değiştirince haritası gelişti?",
    contentQualityReview: {
      status: "pending",
      reviewerName: "",
      reviewedAt: null,
      reviewNotes: "",
      checklist: {
        narrativeArc: false,
        ageFit: false,
        sectionContinuity: false,
        characterConsistency: false,
        languageQuality: false,
        factualAccuracy: false,
        originalityRights: false,
        accessibilityTone: false,
      },
    },
  },
};
